// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGngxgQU4IelTvEwSoF5qpZK0Ya2yJDmo',
    appId: '1:1910279814:web:596aa5d889a2ec4287cb07',
    messagingSenderId: '1910279814',
    projectId: 'moonova-f21ce',
    authDomain: 'moonova-f21ce.firebaseapp.com',
    storageBucket: 'moonova-f21ce.firebasestorage.app',
    measurementId: 'G-0S8TQ5XMQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXQilP3EtV2T8X0Js6Ags34x2tI8Nwchk',
    appId: '1:1910279814:android:22d68dfce3decc9787cb07',
    messagingSenderId: '1910279814',
    projectId: 'moonova-f21ce',
    storageBucket: 'moonova-f21ce.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsm9RBlNhDOZ_TgitpeVdGxT-aP2jMTOs',
    appId: '1:1910279814:ios:5c6fd680480220d987cb07',
    messagingSenderId: '1910279814',
    projectId: 'moonova-f21ce',
    storageBucket: 'moonova-f21ce.firebasestorage.app',
    androidClientId: '1910279814-m8eke20e3cuoj3le0u7lh4ijfmfj0e95.apps.googleusercontent.com',
    iosClientId: '1910279814-4gc6i0fde7earbiviq20u4mjo8bbfrfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.moonova',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsm9RBlNhDOZ_TgitpeVdGxT-aP2jMTOs',
    appId: '1:1910279814:ios:5c6fd680480220d987cb07',
    messagingSenderId: '1910279814',
    projectId: 'moonova-f21ce',
    storageBucket: 'moonova-f21ce.firebasestorage.app',
    androidClientId: '1910279814-m8eke20e3cuoj3le0u7lh4ijfmfj0e95.apps.googleusercontent.com',
    iosClientId: '1910279814-4gc6i0fde7earbiviq20u4mjo8bbfrfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.moonova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGngxgQU4IelTvEwSoF5qpZK0Ya2yJDmo',
    appId: '1:1910279814:web:acf99a3512ab6c3a87cb07',
    messagingSenderId: '1910279814',
    projectId: 'moonova-f21ce',
    authDomain: 'moonova-f21ce.firebaseapp.com',
    storageBucket: 'moonova-f21ce.firebasestorage.app',
    measurementId: 'G-J8Z4HF1N7V',
  );
}
